/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(feeds)'}/followsFeed` | `/followsFeed`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(feeds)'}/publicFeed` | `/publicFeed`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(user)'}/user` | `/user`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(user)'}${'/(editAccount)'}/editAccount` | `/editAccount`; params?: Router.UnknownInputParams; } | { pathname: `/album/newAlbum`; params?: Router.UnknownInputParams; } | { pathname: `/photos/photo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(user)'}/[userId]` | `/[userId]`, params: Router.UnknownInputParams & { userId: string | number; } } | { pathname: `/album/[albumId]`, params: Router.UnknownInputParams & { albumId: string | number; } } | { pathname: `/album/editAlbum/[editId]`, params: Router.UnknownInputParams & { editId: string | number; } } | { pathname: `/photos/[photoId]`, params: Router.UnknownInputParams & { photoId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(feeds)'}/followsFeed` | `/followsFeed`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(feeds)'}/publicFeed` | `/publicFeed`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(user)'}/user` | `/user`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(user)'}${'/(editAccount)'}/editAccount` | `/editAccount`; params?: Router.UnknownOutputParams; } | { pathname: `/album/newAlbum`; params?: Router.UnknownOutputParams; } | { pathname: `/photos/photo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(user)'}/[userId]` | `/[userId]`, params: Router.UnknownOutputParams & { userId: string; } } | { pathname: `/album/[albumId]`, params: Router.UnknownOutputParams & { albumId: string; } } | { pathname: `/album/editAlbum/[editId]`, params: Router.UnknownOutputParams & { editId: string; } } | { pathname: `/photos/[photoId]`, params: Router.UnknownOutputParams & { photoId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(feeds)'}/followsFeed${`?${string}` | `#${string}` | ''}` | `/followsFeed${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(feeds)'}/publicFeed${`?${string}` | `#${string}` | ''}` | `/publicFeed${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(user)'}/user${`?${string}` | `#${string}` | ''}` | `/user${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(user)'}${'/(editAccount)'}/editAccount${`?${string}` | `#${string}` | ''}` | `/editAccount${`?${string}` | `#${string}` | ''}` | `/album/newAlbum${`?${string}` | `#${string}` | ''}` | `/photos/photo${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(feeds)'}/followsFeed` | `/followsFeed`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(feeds)'}/publicFeed` | `/publicFeed`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(user)'}/user` | `/user`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(user)'}${'/(editAccount)'}/editAccount` | `/editAccount`; params?: Router.UnknownInputParams; } | { pathname: `/album/newAlbum`; params?: Router.UnknownInputParams; } | { pathname: `/photos/photo`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}${'/(user)'}/${Router.SingleRoutePart<T>}` | `/${Router.SingleRoutePart<T>}` | `/album/${Router.SingleRoutePart<T>}` | `/album/editAlbum/${Router.SingleRoutePart<T>}` | `/photos/${Router.SingleRoutePart<T>}` | { pathname: `${'/(tabs)'}${'/(user)'}/[userId]` | `/[userId]`, params: Router.UnknownInputParams & { userId: string | number; } } | { pathname: `/album/[albumId]`, params: Router.UnknownInputParams & { albumId: string | number; } } | { pathname: `/album/editAlbum/[editId]`, params: Router.UnknownInputParams & { editId: string | number; } } | { pathname: `/photos/[photoId]`, params: Router.UnknownInputParams & { photoId: string | number; } };
    }
  }
}
